### ISSUE TITLE
dump_window_hierarchy doesn't work on 0.16.0

### ISSUE THREAD

**Issue by jmmercadom** [amplify-education/honeydew#11]
With the version 0.16.0 the device method dum_window_hierarchy is raising an exception.
Follows the error message:

``` ruby
jruby-1.7.3 :005 > Honeydew.current_device.dump_window_hierarchy('/tmp')
Device D1OKCT054577: waiting for honeydew-server to respond
Device D1OKCT054577: honeydew-server is alive and awaiting commands
NoMethodError: undefined method `[]' for true:TrueClass
    from /home/darth/.rvm/gems/jruby-1.7.3@amplify-admin-portal/bundler/gems/honeydew-f680fb04b9a5/lib/honeydew/device_commands.rb:21:in `dump_window_hierarchy'
    from (irb):5:in `evaluate'
    from org/jruby/RubyKernel.java:1066:in `eval'
    from org/jruby/RubyKernel.java:1409:in `loop'
    from org/jruby/RubyKernel.java:1174:in `catch'
    from org/jruby/RubyKernel.java:1174:in `catch'
    from /home/darth/.rvm/gems/jruby-1.7.3@amplify-admin-portal/gems/railties-3.2.12/lib/rails/commands/console.rb:47:in `start'
    from /home/darth/.rvm/gems/jruby-1.7.3@amplify-admin-portal/gems/railties-3.2.12/lib/rails/commands/console.rb:8:in `start'
    from /home/darth/.rvm/gems/jruby-1.7.3@amplify-admin-portal/gems/railties-3.2.12/lib/rails/commands.rb:41:in `(root)'
    from org/jruby/RubyKernel.java:1027:in `require'
    from script/rails:1:in `(root)'
```
